name: DiceFurniture
version: 3.4.6
description: Add some new Objects to the Server
author: Ste3et_C0st
website: http://dicecraft.de
depend: [FurnitureLib]
main: de.Ste3et_C0st.Furniture.Main.main
api-version: 1.13